INSERT INTO users (id, NAME, email, avatar, email_verified_at, PASSWORD, created_at) VALUES (1, 'admin', 'admin@admin', 'mumrita.jpg', NOW(), 'xxx',  NOW());

INSERT INTO blog_theme (id, theme, created_at) VALUES (1, 'Primer tema blog', NOW());

insert into blog_posts (id, title, short_html, html, tags, user_id, image, visible, visible_since, created_at) VALUES(1, 'Primer blog titulo', '
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur elementum tellus, ut congue arcu mattis eget. Nullam cursus semper urna nec tristique. Curabitur nunc purus, finibus laoreet quam in, volutpat tincidunt augue. Quisque ac ante nec lectus tempor luctus. Nullam pellentesque eu augue hendrerit egestas. Curabitur sed dui metus. Ut rhoncus aliquam magna a varius. Fusce a tincidunt nisi. Nunc porta sagittis arcu vel scelerisque. Nulla et feugiat enim. Aliquam placerat quam erat, in feugiat nulla aliquet eu.</p>
<p>Suspendisse aliquet velit quis eros sagittis tempus. Pellentesque bibendum felis velit, ac imperdiet massa feugiat quis. Duis rutrum a dolor eu ullamcorper. Phasellus ornare nisi a justo hendrerit facilisis. Etiam consequat feugiat ultricies. Vivamus at ante nulla. Nulla aliquam sollicitudin augue, non auctor ex lobortis ac. Etiam eu tempor quam. Phasellus eu quam urna. Donec condimentum varius eros. Maecenas nec elit ut enim mollis ultricies. Suspendisse potenti. Cras erat odio, tempus eget leo vitae, faucibus placerat est.</p>
', '
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur elementum tellus, ut congue arcu mattis eget. Nullam cursus semper urna nec tristique. Curabitur nunc purus, finibus laoreet quam in, volutpat tincidunt augue. Quisque ac ante nec lectus tempor luctus. Nullam pellentesque eu augue hendrerit egestas. Curabitur sed dui metus. Ut rhoncus aliquam magna a varius. Fusce a tincidunt nisi. Nunc porta sagittis arcu vel scelerisque. Nulla et feugiat enim. Aliquam placerat quam erat, in feugiat nulla aliquet eu.</p>
<p>Suspendisse aliquet velit quis eros sagittis tempus. Pellentesque bibendum felis velit, ac imperdiet massa feugiat quis. Duis rutrum a dolor eu ullamcorper. Phasellus ornare nisi a justo hendrerit facilisis. Etiam consequat feugiat ultricies. Vivamus at ante nulla. Nulla aliquam sollicitudin augue, non auctor ex lobortis ac. Etiam eu tempor quam. Phasellus eu quam urna. Donec condimentum varius eros. Maecenas nec elit ut enim mollis ultricies. Suspendisse potenti. Cras erat odio, tempus eget leo vitae, faucibus placerat est.</p>
<p>Aliquam ac suscipit neque. Praesent quis arcu risus. Nunc sed semper odio, quis egestas nisi. Donec porta varius ex, ac blandit arcu mollis ut. Phasellus eu interdum erat, id pellentesque nisi. Maecenas porttitor varius arcu, sit amet gravida dui. Phasellus sit amet tellus fringilla, lacinia felis id, tristique arcu. Integer purus odio, aliquam sed lacinia quis, scelerisque a ante. Fusce neque lorem, varius sit amet sollicitudin ultricies, egestas ut ex. Curabitur vitae mi non mauris ornare laoreet. Nulla eget augue id nisi volutpat semper. In ut laoreet nisi. In fermentum scelerisque sapien, quis malesuada sapien semper at.</p>
<blockquote>
    Aliquam sit amet augue augue. Mauris vitae dapibus nulla. Sed condimentum cursus libero, in malesuada neque. In a libero vitae dui gravida ultrices non vel nibh. Phasellus pulvinar nec tellus sit amet pretium. Aliquam erat volutpat. Suspendisse potenti. Cras eu mauris et nulla hendrerit volutpat quis eu eros.
    <small>
        Sam Doe
        <cite title="Source Title">biz inc</cite>
    </small>
</blockquote>
<p>Etiam scelerisque sem mi, et tristique turpis posuere eget. Donec consectetur metus vulputate, placerat urna et, semper elit. Vestibulum ornare risus vel dapibus tristique. Vestibulum ipsum arcu, imperdiet in ipsum sit amet, porttitor efficitur odio. Nunc ut lorem eu tellus pulvinar hendrerit. Suspendisse potenti. Fusce magna lacus, faucibus sit amet lorem in, sollicitudin luctus enim. Praesent vitae ex in metus ullamcorper luctus. Nunc nibh eros, dapibus quis ultricies sed, blandit in justo. Fusce auctor neque justo, sed efficitur purus vulputate sit amet. Duis placerat, enim eget tempor maximus, nisi ex efficitur enim, a congue nisl ligula vitae justo. In enim felis, pellentesque eget orci at, feugiat pulvinar turpis. Ut suscipit quis risus vel interdum. In placerat pellentesque urna ut porta.</p>
<p>Integer purus orci, lobortis ut urna ut, rutrum euismod enim. Fusce commodo scelerisque convallis. Aenean congue semper condimentum. Praesent pulvinar ut ipsum quis pretium. Integer ut sem nec sapien maximus sodales nec aliquet orci. Integer a eros nec magna sollicitudin luctus. Sed facilisis iaculis dignissim. Vivamus risus elit, finibus non turpis nec, sodales semper lorem. Duis metus ante, lacinia nec feugiat ac, consectetur nec leo. Suspendisse malesuada in dui et venenatis.</p>
<p>Vestibulum viverra mollis venenatis. Phasellus ullamcorper, magna sed egestas aliquet, ex lorem vestibulum nisi, quis tristique turpis sem eu ex. Quisque bibendum augue vel leo varius hendrerit. In mollis dignissim egestas. Nam et nisl varius, elementum augue vitae, laoreet ex. Nam egestas laoreet rhoncus. Praesent lacinia ultricies urna, at congue ex condimentum in.</p>
<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut vitae aliquam erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed nisi non urna vulputate elementum at sed nisl. Duis in sem luctus, condimentum quam a, dictum nibh. Suspendisse venenatis lacus rutrum luctus pretium. Duis in purus pellentesque, vehicula libero eget, tempus nunc. Donec lacinia, tortor at ornare laoreet, erat odio tempor turpis, a interdum lacus purus non eros. Curabitur bibendum orci enim, in facilisis eros sagittis non. Maecenas et lobortis ligula, id bibendum lorem. Vivamus in ligula vitae sapien pulvinar porttitor. Morbi tincidunt eros sed felis porttitor, id interdum magna fringilla. Morbi aliquam justo quis iaculis sodales.</p>
<p>Etiam eu tristique quam. Donec iaculis laoreet dolor, ut ullamcorper lacus efficitur eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce quis neque at sem consequat vulputate nec eu ipsum. Donec ornare fermentum urna nec eleifend. Duis tincidunt ligula in elit convallis, eu faucibus quam mattis. Maecenas nec elementum elit. Sed finibus quam sed ex auctor, id dignissim risus lacinia. Vestibulum at nisi nunc. Ut viverra, libero id sagittis volutpat, nibh ligula imperdiet nibh, sed vehicula massa purus nec dui. Fusce placerat arcu ut quam tincidunt malesuada. Morbi felis orci, volutpat eu consequat ut, vestibulum luctus odio. Praesent luctus sodales volutpat. Proin dolor odio, condimentum in elementum in, dignissim venenatis ligula. Nunc ipsum magna, efficitur quis tincidunt ac, auctor eget ligula. In ligula ipsum, dictum vel rutrum maximus, mollis eu sapien.</p>
<div class="row-fluid">
    <div class="span6">
        <p class="lead">
        Phasellus sollicitudin viverra nunc volutpat tincidunt.
        </p>
        <p>
        In in purus nisi, sed pulvinar elit. Pellentesque mollis, ipsum a elementum porta, turpis sem volutpat lectus, ac bibendum nisi felis et tellus. Mauris feugiat urna nec velit laoreet tempus. Sed eu hendrerit tellus. Sed dapibus nunc vel mi hendrerit pulvinar. Nulla semper, urna vel gravida tincidunt, diam ipsum porta nibh, ac dictum urna lorem ac quam. Nulla at leo justo. Vestibulum vel quam nunc, ac mollis purus. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
        </p>
    </div>
    <div class="span6">
        <img class="img-polaroid" src="images/assets/landscapes/landscape-7-300x300.jpg">
    </div>
</div>
<p>Aenean turpis odio, laoreet non arcu id, porta aliquam tortor. Morbi pellentesque leo id diam mattis vehicula. Cras sodales nisl eu iaculis vehicula. Mauris hendrerit posuere nunc in placerat. Pellentesque eu enim eget nibh cursus viverra. Sed a ultricies sapien, in aliquam mi. Donec viverra, ligula in blandit efficitur, lorem justo pulvinar erat, eget finibus arcu tortor lacinia justo. Aenean in mollis nibh. Sed varius convallis risus dictum tincidunt. Proin aliquet bibendum odio, ac vehicula nisi mollis sit amet.</p>
<p>Sed dignissim leo non mi semper tempus. In tempus sollicitudin nulla, eget scelerisque lacus sodales ut. Nullam in interdum sapien. Sed fringilla turpis sodales, semper ligula nec, placerat libero. Aenean nec nisi aliquet, dictum urna id, ullamcorper nisl. Nam in nisl faucibus, lobortis augue ut, finibus erat. Vivamus vel auctor est. Nulla pharetra ut sapien vel ultricies. Morbi et metus in nulla suscipit faucibus. Nullam sed posuere eros. Morbi eu egestas lacus, ut fermentum velit. Nullam ipsum risus, aliquam nec nulla et, posuere rutrum ipsum.</p>
<p>Curabitur ac ipsum aliquam, fringilla lacus sit amet, rhoncus urna. Nunc sagittis sit amet erat ac tempus. Etiam sed nibh vel ante congue pulvinar vel non.</p>
', 'primer,blog,titulo', 1, 'landscape-1-800x400.jpg', 1, NOW(), NOW());

insert into blog_post (id, title, short_html, html, tags, user_id, image, visible, visible_since, created_at) VALUES(2, 'Segundo blog titulo', '
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur elementum tellus, ut congue arcu mattis eget. Nullam cursus semper urna nec tristique. Curabitur nunc purus, finibus laoreet quam in, volutpat tincidunt augue. Quisque ac ante nec lectus tempor luctus. Nullam pellentesque eu augue hendrerit egestas. Curabitur sed dui metus. Ut rhoncus aliquam magna a varius. Fusce a tincidunt nisi. Nunc porta sagittis arcu vel scelerisque. Nulla et feugiat enim. Aliquam placerat quam erat, in feugiat nulla aliquet eu.</p>
<p>Suspendisse aliquet velit quis eros sagittis tempus. Pellentesque bibendum felis velit, ac imperdiet massa feugiat quis. Duis rutrum a dolor eu ullamcorper. Phasellus ornare nisi a justo hendrerit facilisis. Etiam consequat feugiat ultricies. Vivamus at ante nulla. Nulla aliquam sollicitudin augue, non auctor ex lobortis ac. Etiam eu tempor quam. Phasellus eu quam urna. Donec condimentum varius eros. Maecenas nec elit ut enim mollis ultricies. Suspendisse potenti. Cras erat odio, tempus eget leo vitae, faucibus placerat est.</p>
', '
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur elementum tellus, ut congue arcu mattis eget. Nullam cursus semper urna nec tristique. Curabitur nunc purus, finibus laoreet quam in, volutpat tincidunt augue. Quisque ac ante nec lectus tempor luctus. Nullam pellentesque eu augue hendrerit egestas. Curabitur sed dui metus. Ut rhoncus aliquam magna a varius. Fusce a tincidunt nisi. Nunc porta sagittis arcu vel scelerisque. Nulla et feugiat enim. Aliquam placerat quam erat, in feugiat nulla aliquet eu.</p>
<p>Suspendisse aliquet velit quis eros sagittis tempus. Pellentesque bibendum felis velit, ac imperdiet massa feugiat quis. Duis rutrum a dolor eu ullamcorper. Phasellus ornare nisi a justo hendrerit facilisis. Etiam consequat feugiat ultricies. Vivamus at ante nulla. Nulla aliquam sollicitudin augue, non auctor ex lobortis ac. Etiam eu tempor quam. Phasellus eu quam urna. Donec condimentum varius eros. Maecenas nec elit ut enim mollis ultricies. Suspendisse potenti. Cras erat odio, tempus eget leo vitae, faucibus placerat est.</p>
<p>Aliquam ac suscipit neque. Praesent quis arcu risus. Nunc sed semper odio, quis egestas nisi. Donec porta varius ex, ac blandit arcu mollis ut. Phasellus eu interdum erat, id pellentesque nisi. Maecenas porttitor varius arcu, sit amet gravida dui. Phasellus sit amet tellus fringilla, lacinia felis id, tristique arcu. Integer purus odio, aliquam sed lacinia quis, scelerisque a ante. Fusce neque lorem, varius sit amet sollicitudin ultricies, egestas ut ex. Curabitur vitae mi non mauris ornare laoreet. Nulla eget augue id nisi volutpat semper. In ut laoreet nisi. In fermentum scelerisque sapien, quis malesuada sapien semper at.</p>
<blockquote>
    Aliquam sit amet augue augue. Mauris vitae dapibus nulla. Sed condimentum cursus libero, in malesuada neque. In a libero vitae dui gravida ultrices non vel nibh. Phasellus pulvinar nec tellus sit amet pretium. Aliquam erat volutpat. Suspendisse potenti. Cras eu mauris et nulla hendrerit volutpat quis eu eros.
    <small>
        Sam Doe
        <cite title="Source Title">biz inc</cite>
    </small>
</blockquote>
<p>Etiam scelerisque sem mi, et tristique turpis posuere eget. Donec consectetur metus vulputate, placerat urna et, semper elit. Vestibulum ornare risus vel dapibus tristique. Vestibulum ipsum arcu, imperdiet in ipsum sit amet, porttitor efficitur odio. Nunc ut lorem eu tellus pulvinar hendrerit. Suspendisse potenti. Fusce magna lacus, faucibus sit amet lorem in, sollicitudin luctus enim. Praesent vitae ex in metus ullamcorper luctus. Nunc nibh eros, dapibus quis ultricies sed, blandit in justo. Fusce auctor neque justo, sed efficitur purus vulputate sit amet. Duis placerat, enim eget tempor maximus, nisi ex efficitur enim, a congue nisl ligula vitae justo. In enim felis, pellentesque eget orci at, feugiat pulvinar turpis. Ut suscipit quis risus vel interdum. In placerat pellentesque urna ut porta.</p>
<p>Integer purus orci, lobortis ut urna ut, rutrum euismod enim. Fusce commodo scelerisque convallis. Aenean congue semper condimentum. Praesent pulvinar ut ipsum quis pretium. Integer ut sem nec sapien maximus sodales nec aliquet orci. Integer a eros nec magna sollicitudin luctus. Sed facilisis iaculis dignissim. Vivamus risus elit, finibus non turpis nec, sodales semper lorem. Duis metus ante, lacinia nec feugiat ac, consectetur nec leo. Suspendisse malesuada in dui et venenatis.</p>
<p>Vestibulum viverra mollis venenatis. Phasellus ullamcorper, magna sed egestas aliquet, ex lorem vestibulum nisi, quis tristique turpis sem eu ex. Quisque bibendum augue vel leo varius hendrerit. In mollis dignissim egestas. Nam et nisl varius, elementum augue vitae, laoreet ex. Nam egestas laoreet rhoncus. Praesent lacinia ultricies urna, at congue ex condimentum in.</p>
<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut vitae aliquam erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed nisi non urna vulputate elementum at sed nisl. Duis in sem luctus, condimentum quam a, dictum nibh. Suspendisse venenatis lacus rutrum luctus pretium. Duis in purus pellentesque, vehicula libero eget, tempus nunc. Donec lacinia, tortor at ornare laoreet, erat odio tempor turpis, a interdum lacus purus non eros. Curabitur bibendum orci enim, in facilisis eros sagittis non. Maecenas et lobortis ligula, id bibendum lorem. Vivamus in ligula vitae sapien pulvinar porttitor. Morbi tincidunt eros sed felis porttitor, id interdum magna fringilla. Morbi aliquam justo quis iaculis sodales.</p>
<p>Etiam eu tristique quam. Donec iaculis laoreet dolor, ut ullamcorper lacus efficitur eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce quis neque at sem consequat vulputate nec eu ipsum. Donec ornare fermentum urna nec eleifend. Duis tincidunt ligula in elit convallis, eu faucibus quam mattis. Maecenas nec elementum elit. Sed finibus quam sed ex auctor, id dignissim risus lacinia. Vestibulum at nisi nunc. Ut viverra, libero id sagittis volutpat, nibh ligula imperdiet nibh, sed vehicula massa purus nec dui. Fusce placerat arcu ut quam tincidunt malesuada. Morbi felis orci, volutpat eu consequat ut, vestibulum luctus odio. Praesent luctus sodales volutpat. Proin dolor odio, condimentum in elementum in, dignissim venenatis ligula. Nunc ipsum magna, efficitur quis tincidunt ac, auctor eget ligula. In ligula ipsum, dictum vel rutrum maximus, mollis eu sapien.</p>
<div class="row-fluid">
    <div class="span6">
        <p class="lead">
        Phasellus sollicitudin viverra nunc volutpat tincidunt.
        </p>
        <p>
        In in purus nisi, sed pulvinar elit. Pellentesque mollis, ipsum a elementum porta, turpis sem volutpat lectus, ac bibendum nisi felis et tellus. Mauris feugiat urna nec velit laoreet tempus. Sed eu hendrerit tellus. Sed dapibus nunc vel mi hendrerit pulvinar. Nulla semper, urna vel gravida tincidunt, diam ipsum porta nibh, ac dictum urna lorem ac quam. Nulla at leo justo. Vestibulum vel quam nunc, ac mollis purus. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
        </p>
    </div>
    <div class="span6">
        <img class="img-polaroid" src="images/assets/landscapes/landscape-7-300x300.jpg">
    </div>
</div>
<p>Aenean turpis odio, laoreet non arcu id, porta aliquam tortor. Morbi pellentesque leo id diam mattis vehicula. Cras sodales nisl eu iaculis vehicula. Mauris hendrerit posuere nunc in placerat. Pellentesque eu enim eget nibh cursus viverra. Sed a ultricies sapien, in aliquam mi. Donec viverra, ligula in blandit efficitur, lorem justo pulvinar erat, eget finibus arcu tortor lacinia justo. Aenean in mollis nibh. Sed varius convallis risus dictum tincidunt. Proin aliquet bibendum odio, ac vehicula nisi mollis sit amet.</p>
<p>Sed dignissim leo non mi semper tempus. In tempus sollicitudin nulla, eget scelerisque lacus sodales ut. Nullam in interdum sapien. Sed fringilla turpis sodales, semper ligula nec, placerat libero. Aenean nec nisi aliquet, dictum urna id, ullamcorper nisl. Nam in nisl faucibus, lobortis augue ut, finibus erat. Vivamus vel auctor est. Nulla pharetra ut sapien vel ultricies. Morbi et metus in nulla suscipit faucibus. Nullam sed posuere eros. Morbi eu egestas lacus, ut fermentum velit. Nullam ipsum risus, aliquam nec nulla et, posuere rutrum ipsum.</p>
<p>Curabitur ac ipsum aliquam, fringilla lacus sit amet, rhoncus urna. Nunc sagittis sit amet erat ac tempus. Etiam sed nibh vel ante congue pulvinar vel non.</p>
', 'segundo,blog,titulo', 1, 'landscape-1-800x400.jpg', 1, NOW(), NOW());

insert into blog_theme_blog_post (id, blog_theme_id, blog_post_id) values (1, 1, 1);

INSERT INTO blog_image_header (id, filename, title, blog_post_id, created_at) VALUES (1, 'landscape-1-800x400.jpg', 'landscape-1-800x400', 1, NOW());
INSERT INTO blog_image_header (id, filename, title, blog_post_id, created_at) VALUES (2, 'landscape-3-800x400.jpg', 'landscape-3-800x400', 1, NOW());
INSERT INTO blog_image_header (id, filename, title, blog_post_id, created_at) VALUES (3, 'landscape-6-800x400.jpg', 'landscape-6-800x400', 1, NOW());

INSERT INTO video_models (id, name, iframe_code, created_at) VALUES (1, 'youtube', '<iframe width="560" height="315" src="https://www.youtube.com/embed/[[id]]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', NOW());
INSERT INTO video_models (id, name, iframe_code, created_at) VALUES (2, 'vimeo', '<iframe allowFullScreen="" frameborder="0" height="4 0" mozallowfullscreen="" src="http://player.vimeo.com/video/[[id]]?title=[[title]]&amp;amp;byline=0&amp;amp;color=42576a" webkitAllowFullScreen="" width="800"></iframe>', NOW());
INSERT INTO video_models (id, name, iframe_code, created_at) VALUES (3, 'facebook', '<iframe src="[[id]]" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>', NOW());

